name: lncwebb
channels:
  - bioconda
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - gmap=2021.08.25
  - gffcompare=0.11.2
  - bedops=2.4.39
  - pybedtools=0.8.2
  - python=3.9.0
  - r-base=4.2.0
  - blast=2.12.0
  - pip
  - pip:
    - pandas
    - plotly
    - streamlit-plotly-events
    - matplotlib
    - biopython
    - scikit-learn
