channels:
  - r
  - conda-forge
  - bioconda/label/cf201901
  - bioconda
  - defaults
dependencies:
  - blast=2.5.0
  - gmap=2021.08.25
  - python=3.9.16
  - qt=5.6.3
  - r-abind=1.4_5
  - pip:
      - altair==5.0.1
      - annotated-types==0.5.0
      - attrs==23.1.0
      - blinker==1.6.2
      - cachetools==5.3.1
      - click==8.1.6
      - contourpy==1.1.0
      - cycler==0.11.0
      - decorator==5.1.1
      - distlib==0.3.7
      - filelock==3.12.2
      - fonttools==4.42.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - jinja2==3.1.2
      - joblib==1.3.1
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - kiwisolver==1.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mdurl==0.1.2
      - mmseqs==1.0.0
      - numpy==1.25.1
      - pandas==1.5.3
      - pillow==9.5.0
      - platformdirs==3.10.0
      - plotly==5.15.0
      - protobuf==4.24.0
      - pyarrow==12.0.1
      - pydantic==2.1.1
      - pydantic-core==2.4.0
      - pydeck==0.8.0
      - pygments==2.16.1
      - pympler==1.0.1
      - pyopenms==3.0.0
      - pyparsing==3.0.9
      - pyteomics==4.6
      - pytz==2023.3
      - pytz-deprecation-shim==0.1.0.post0
      - referencing==0.30.2
      - rich==13.5.2
      - rpds-py==0.9.2
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - smmap==5.0.0
      - sqlitedict==1.7.0
      - streamlit==1.25.0
      - streamlit-plotly-events==0.0.6
      - streamlit-pydantic==0.6.0
      - tenacity==8.2.2
      - threadpoolctl==3.2.0
      - toml==0.10.2
      - tornado==6.3.2
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - tzlocal==4.3.1
      - validators==0.20.0
      - virtualenv==20.24.2
      - watchdog==3.0.0
      - wget==3.2
      - zipp==3.16.2
